[build]
command = "pip install --upgrade pip && pip install -r requirements-deploy.txt && streamlit run app.py"
publish = "."

[build.environment]
PYTHON_VERSION = "3.11.7"
PYTHON_FLAGS = "--no-cache-dir"

[[redirects]]
from = "/*"
to = "/"
status = 200
force = true
