[build]
command = "python -m pip install --upgrade pip && pip install -r requirements-deploy.txt && streamlit run app.py"
publish = "public"

[build.environment]
PYTHON_VERSION = "3.9"

[[redirects]]
from = "/*"
to = "/"
status = 200
