[build]
command = "pip install -r requirements-minimal.txt && mkdir -p public && cp -r * public/ || true"
publish = "public"

[build.environment]
PYTHON_VERSION = "3.9"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
